### PR TITLE
Tv on the internet

### PR DESCRIPTION
**Pull request by daleinen7**
Transparency overlay is more distracting to me than helpful, but I put it in place in case you had ideas on how to improve it. Originally it matched the SVG icon you found with a hard line in the middle, but that looked terrible to me so I turned it into an gradient. Lemme know what you think overall. 

[reference](https://upload.wikimedia.org/wikipedia/commons/d/d4/Circle-icons-tv.svg)

### CODE REVIEW

**Review by kndshein — CHANGES_REQUESTED** [review]
There are a few changes I'd like to bring up -- nothing to do with your implementations, just design rework.

1. The dial button should be different from the button to not draw away attention. Plus CTA buttons should have its own color.
2. The shadow on the dials are too dark and harsh
3. Could you make the shadow the same angle as the button?
4. The "TV screen" just looks like bluish grey foggy filter, is that right?
image

**Comment by daleinen7** [comment]
1-3 yes also 4 yes. Maybe I can add a third super bright thin white line to sort of act as a real reflection?

**Comment by daleinen7** [comment]
alternately skip the transparency entirely.

**Comment by kndshein** [comment]
I think remove "transparency" and give that "reflection" another shot.

**Comment by daleinen7** [comment]
I don't know what you mean by remove the transparency and try the reflection. When I say transparency, I mean a CSS div in front of the image from graphql. Here is another attempt though I am not thrilled with it. What do you think?

**Comment by kndshein** [comment]
Hmm. not a fan of it either. Could you implement it like this where it's "lighter" for half of it?
image
Remove the "transparency" div, i'd say. Just the "reflection" that lightens half of the "screen" would be nice i think!

**Review by kndshein — APPROVED** [review]

**Pull request merged**
